name: app_name
description: Who Used My Phone Mobile App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1

  provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mockito: ^5.4.2
  test: ^1.24.1
  very_good_analysis: ^5.1.0  # Contains the same as flutter_lints + more

flutter:
  uses-material-design: true
